### ISSUE TITLE
No option to connect to a password protected MPD

### ISSUE THREAD

**Issue by sobornostea** [Difegue/Stylophone#19]
There is currently no option to connect to a password protected mpd server, which is kinda useful security wise

**Comment by Difegue** [comment]
Hm, I didn't implement MPD passwords since they're kinda insecure to begin with (sent completely over cleartext, no identity check etc), but if there's enough demand for it I'll add it in eventually.  

It's just a matter of implementing the [password](https://www.musicpd.org/doc/html/protocol.html#connection-settings) command in MpcNET and sending it if there's a password saved in Stylophone settings.

**Comment by Difegue** [comment]
I've added this while re-architecturing the app and it'll be in the upcoming v2, set to release at the end of the month. 👍
